### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [kmaki565/EventLook#33]
Does this work with Win 7?

Thanks.

**Comment by kmaki565** [comment]
I have not tested with Windows 7. It will probably run as .NET 6 is currently supported on Windows 7 according to [this](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md). 
Please try the latest artifact in [Actions](https://github.com/kmaki565/EventLook/actions) and let me know if any problems.
