### ISSUE TITLE
Open Classic Event Logs (.evt) from command line or Explorer

### ISSUE THREAD

**Issue by XiaoP76** [kmaki565/EventLook#75]
It would be great if it were possible to pass the path to an event file as a parameter on the command line, like this:
EventLook.exe "d:\!WIP\240906 1744\Diag\EventLogs\Platform-PowerManagement_Operational.evt"

**Comment by XiaoP76** [comment]
Hi K.Maki,

thanks for the answer. You are right, .evtx files can be passed on the
command line.
But since EventLook works with the older .evt format just fine, why
restricting the extension just to .evtx ?
I use it as a viewer for .evt files from a legacy system, where they are a
part of a diagnosis package.

Best regards

Petr

Am Sa., 14. Sept. 2024 um 14:37 Uhr schrieb K. Maki <
***@***.***>:

**Comment by kmaki565** [comment]
Hi @XiaoP76,
Since I don't have any .evt files (**Classic** Event Log) in hand, can you test with your files?
If all functions in EventLook work well, please open a pull request to add the extension when handling the command line.

**Comment by XiaoP76** [comment]
Hi @kmaki565, I'm sorry, but it turns out that the .evt files that I have are actually .evtx files with the wrong extension. They simply forgot to change the extension after they switched from Windows XP to Windows 7.
I found a bug though - files with uppercase extension .EVTX can't be opened from the command line. I'll fix it with a separate pull request.
